### ISSUE TITLE
Touch 

### ISSUE THREAD

**Issue by Pandan** [ZwickTheGreat/feathers-maps#1]
First of thanks for a great contribution to the starling/feathers community.
One thing that I have noticed when testing on device is that touch(drag/scale) seems to only work for tiles that have loaded content in them. Would be great if it picked up touches on tiles that haven't finished loading the content.
I had a quick look in the code, tested adding a background quad in the MapTile but it did not seem to help a lot. Any suggestions where I should start looking?

**Comment by ZwickTheGreat** [comment]
Hi, you are right.
The problem is in TouchSheet.. Maybe try to override it's hitTest function and always return true if touch is in map bounds.
I will try to look at it as well.

**Comment by Pandan** [comment]
Thanks for the fix!
