### ISSUE TITLE
Is it possible to be able to tell the direction from one point to another point.

### ISSUE THREAD

**Issue by mindthstudio** [ZwickTheGreat/feathers-maps#5]
![ccc](https://cloud.githubusercontent.com/assets/8232957/14238786/0ec76df8-fa5f-11e5-8159-5b3cedaf7695.jpg)

**Comment by xojltoh** [comment]
As i know, you cannot do it in existing version.
But you can request a route from google service https://developers.google.com/maps/documentation/javascript/directions?hl=en#GeocodedWaypoints
And draw lines above the map, somewhere under markers layer

**Comment by ZwickTheGreat** [comment]
It's not supported.

As xojltoh said - you can make it via your own layer and draw directions there.

**Comment by mindthstudio** [comment]
Thank you very much.

**Comment by 22Round** [comment]
@ZwickTheGreat Hi, do you plan to support such a feature? 
I have a project where I am going to use your map and have a same issue.

thanks :)
