### ISSUE TITLE
Style Map

### ISSUE THREAD

**Issue by varadig** [ZwickTheGreat/feathers-maps#6]
Hi!

There is any option to style map, like javascript API map styler?

thanks!
https://developers.google.com/maps/documentation/javascript/styling#creating_a_styledmaptype

**Comment by ZwickTheGreat** [comment]
Hi. Unfortunaly not.
Feathers Maps projects is firstly tiled based (TMS) map renderer, not Google maps renderer.

Actually - Google TMS is not official - use it on own risk. :-)
